/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestiunemagazin;

import static gestiunemagazin.TotalValueFile.TotalValueFile;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.lang.reflect.Method;
import java.util.logging.Level;
import java.util.logging.Logger;
import static jdk.internal.org.objectweb.asm.commons.Method.getMethod;

/**
 *
 * @author Florin M
 */
public class TransactionsUI extends javax.swing.JFrame {
    
    private float totalValue;
    public void setTotalValue(float totalValue) {
        this.totalValue = totalValue;
    }
    public float getTotalValue() {
        return totalValue;
    }
    /**
     * Creates new form TransactionsUI
     */
    public TransactionsUI() {
        initComponents();
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codeBarInput = new java.awt.TextField();
        InsertCodeBar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        itemNameLabel = new javax.swing.JLabel();
        itemPriceLabel = new javax.swing.JLabel();
        totalValueLabel = new javax.swing.JLabel();
        endTransactionButton = new javax.swing.JButton();
        ItemQuantityInput = new java.awt.TextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Insert codebar");

        codeBarInput.setText("codebar");
        codeBarInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeBarInputActionPerformed(evt);
            }
        });

        InsertCodeBar.setText("Insert");
        InsertCodeBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertCodeBarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Item:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Price:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Total:");

        itemNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemNameLabel.setText("ItemName");

        itemPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemPriceLabel.setText("ItemPrice");

        totalValueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalValueLabel.setText("TotalValue");

        endTransactionButton.setText("End transaction");
        endTransactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTransactionButtonActionPerformed(evt);
            }
        });

        ItemQuantityInput.setText("1");
        ItemQuantityInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemQuantityInputActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quantity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalValueLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(codeBarInput, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ItemQuantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(InsertCodeBar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(endTransactionButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(itemNameLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(itemPriceLabel)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeBarInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemQuantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertCodeBar))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(itemNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(itemPriceLabel))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalValueLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41)
                .addComponent(endTransactionButton)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codeBarInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeBarInputActionPerformed
        
    }//GEN-LAST:event_codeBarInputActionPerformed

    private void InsertCodeBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertCodeBarActionPerformed
        //System.out.println("Next item button pressed");
        codeBarInput.setText(codeBarInput.getText()); 
        java.lang.String codeBarText = codeBarInput.getText();
        //System.out.println(codeBarText); 
        DBManager con = new DBManager();
        String updateQuery = con.GetScriptFile("UpdateProductQuantity.sql");
        System.out.println("-------");
        //System.out.println(updateQuery);
        String iQ = ItemQuantityInput.getText();
        int itemQuantity = Integer.parseInt(iQ);
        System.out.println("Q: " + itemQuantity);
        con.UpdateItemQuantity(updateQuery,codeBarText,itemQuantity);
        String getPriceQuery = con.GetScriptFile("SelectProductVariables.sql");
        Product prod = con.SelectProductVariables(getPriceQuery, codeBarText, itemQuantity);
        //System.out.println(prod.getProductName());
        itemNameLabel.setText(itemQuantity + " X " + prod.getProductName());
        float priceXQuantity = itemQuantity * (prod.getProductPrice());
        String priceXQuantityString = Float.toString(priceXQuantity);
        itemPriceLabel.setText(priceXQuantity + " RON");
        
        String productName = prod.getProductName();
        int productQuantity = itemQuantity;
        float productPrice = prod.getProductPrice();
        
        //TotalValueFile.TotalValueFile(priceString);
        float totalValue = TotalValueFile(productName, productQuantity, productPrice, priceXQuantityString);
        //System.out.println("===" + totalValue);
        String totalValueString = Float.toString(totalValue);
        totalValueLabel.setText(totalValueString);
        setTotalValue(totalValue);
        
        
        
        //float totalValue = 0;
        //totalValue = totalValue + priceXQuantity;
        //String totalValueString = Float.toString(totalValue);
        //totalValueLabel.setText(totalValueString);
        
    }//GEN-LAST:event_InsertCodeBarActionPerformed

    private void ItemQuantityInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemQuantityInputActionPerformed
        // TODO add your handling code here:
        ItemQuantityInput.setText("1"); 
        int itemQuantity = Integer.parseInt(ItemQuantityInput.getText());
        System.out.println(itemQuantity);
        float totalValue = 0;
        //totalValue = totalValue + priceXQuantity;
        String totalValueString = Float.toString(totalValue);
        totalValueLabel.setText(totalValueString);
        
    }//GEN-LAST:event_ItemQuantityInputActionPerformed

    private void endTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTransactionButtonActionPerformed
        System.out.println("TotalValue: " + totalValue);
        EndTransaction.EndTransaction(totalValue);
    }//GEN-LAST:event_endTransactionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionsUI().setVisible(true);
                DBManager conn = new DBManager();
                PrintWriter clearTotalValueFile;
                PrintWriter clearBonFiscalFile;
                try {
                    clearTotalValueFile = new PrintWriter("totalValue.txt");
                    clearTotalValueFile.close();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(TransactionsUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    clearBonFiscalFile = new PrintWriter("bonFiscal.txt");
                    clearBonFiscalFile.close();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(TransactionsUI.class.getName()).log(Level.SEVERE, null, ex);
                }

                
                /*
                int x = a.getStudentAge("123");
                int y = a.getStudentAge("456");
                */
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InsertCodeBar;
    private java.awt.TextField ItemQuantityInput;
    private java.awt.TextField codeBarInput;
    private javax.swing.JButton endTransactionButton;
    private javax.swing.JLabel itemNameLabel;
    private javax.swing.JLabel itemPriceLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel totalValueLabel;
    // End of variables declaration//GEN-END:variables
}
